version: '3'
services:

  ##############################################
  # PHP
  ##############################################
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway

  ##############################################
  # NGINX
  ##############################################
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  ##############################################
  # MYSQL
  ##############################################
  db:
    image: mysql:8
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/logs:/var/log/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: amintases
      MYSQL_PASSWORD: password

  ##############################################
  # PMA
  ##############################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - db
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    volumes:
        - ./docker/phpmyadmin/sessions:/sessions