version: '3'
services:

  ##############################################
  # PHP
  ##############################################
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway

  ##############################################
  # CRON
  ##############################################
  scheduler:
    build:
      context: docker/php
      dockerfile: Dockerfile
      target: scheduler
    volumes:
      - ./src:/var/www

  ##############################################
  # NGINX
  ##############################################
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  ##############################################
  # MYSQL
  ##############################################
  db:
    image: mysql:8
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my_db.sql:/my_db.sql
    - ./docker/logs:/var/log/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: amintases
      MYSQL_PASSWORD: password

  ##############################################
  # PMA
  ##############################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8080:80"
    links:
        - db
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
    volumes:
        - ./docker/phpmyadmin/sessions:/sessions

  ##############################################
  # Elasticsearch
  ##############################################
  elasticsearch:
    image: elasticsearch:8.12.0
    depends_on:
      - php
    environment:
      - "discovery.type=single-node"
      - "node.name=cluster1-node1"
      - "xpack.license.self_generated.type=basic"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
#      - ./docker/elastic:/usr/share/elasticsearch/data
      - ./docker/logs:/usr/share/elasticsearch/logs

  ##############################################
  # Kibana
  ##############################################
  kibana:
    image: kibana:8.12.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch